In [2]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

## Data Generation

In [3]:
train_samples = [] # age of person ( between 13 and 100) and whether they experienced side effects on taking a drug
train_labels = [] # 1 - did experience side effects ; 0 - did not experience side effects

In [4]:
for i in range(50):
    #5% of young people experienced side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    #5% of older people did not experience side effects
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)
    
for i in range(1000):
    #95% of young people did not experience side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    #95% of older people did experience side effects
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)

In [5]:
for i in train_samples:
    print(i)

27
69
58
68
22
99
51
98
13
95
57
82
25
89
52
97
38
91
24
87
51
68
15
100
41
69
38
77
49
78
50
92
28
75
23
97
21
95
49
75
38
69
39
90
21
72
56
71
40
71
45
76
34
92
30
95
49
94
52
92
33
96
52
85
57
67
27
81
25
77
33
100
60
83
14
93
32
79
39
80
48
78
40
67
53
87
33
95
48
81
58
90
17
69
13
68
53
71
37
71
54
90
32
77
37
77
56
67
13
75
40
70
34
71
56
68
54
98
54
74
35
80
17
82
27
65
58
94
18
95
13
79
29
71
42
82
35
77
58
96
18
69
53
71
31
85
60
96
55
78
27
83
45
77
37
99
38
77
44
99
49
75
41
91
25
80
58
76
47
91
34
89
26
90
56
80
50
85
41
66
13
93
56
75
43
97
40
95
29
100
51
86
41
91
14
82
33
71
23
84
56
96
26
97
14
70
62
91
47
89
24
81
61
75
58
96
25
93
47
86
45
66
64
97
53
89
30
81
31
65
43
91
62
66
36
92
52
70
27
66
13
70
22
83
34
86
60
74
64
95
64
81
27
90
41
98
32
66
16
93
37
75
21
81
33
68
56
65
51
99
37
68
47
98
59
91
19
66
43
67
63
92
45
89
55
96
61
95
13
88
51
97
63
72
14
70
41
91
64
73
44
89
38
81
27
87
39
85
57
91
21
78
39
81
23
70
18
83
52
81
36
94
22
72
37
74
20
77
23
81
62
72
4

## Data processing

In [6]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

In [7]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [8]:
print(scaled_train_samples)

[[0.20689655]
 [0.40229885]
 [0.93103448]
 ...
 [0.88505747]
 [0.35632184]
 [0.87356322]]


## Create ANN using Keras API (Tensorflow backend)

In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [10]:
model = Sequential([Dense(units=16,input_shape=(1,),activation='relu'),
                   Dense(units=32,activation='relu'),
                   Dense(units=2,activation='softmax')])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


## Train Neural Network using the Keras API integrated with Tensorflow

In [12]:
model.compile(optimizer= Adam(learning_rate=0.0001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [13]:
model.fit(x=scaled_train_samples,y=train_labels,batch_size=10,epochs=30,shuffle=True,verbose=2)

Epoch 1/30
210/210 - 0s - loss: 0.6898 - accuracy: 0.5357
Epoch 2/30
210/210 - 0s - loss: 0.6649 - accuracy: 0.6110
Epoch 3/30
210/210 - 0s - loss: 0.6402 - accuracy: 0.6495
Epoch 4/30
210/210 - 0s - loss: 0.6157 - accuracy: 0.6829
Epoch 5/30
210/210 - 0s - loss: 0.5901 - accuracy: 0.7214
Epoch 6/30
210/210 - 0s - loss: 0.5618 - accuracy: 0.7662
Epoch 7/30
210/210 - 0s - loss: 0.5331 - accuracy: 0.7962
Epoch 8/30
210/210 - 0s - loss: 0.5048 - accuracy: 0.8195
Epoch 9/30
210/210 - 0s - loss: 0.4777 - accuracy: 0.8371
Epoch 10/30
210/210 - 0s - loss: 0.4521 - accuracy: 0.8562
Epoch 11/30
210/210 - 0s - loss: 0.4284 - accuracy: 0.8638
Epoch 12/30
210/210 - 0s - loss: 0.4069 - accuracy: 0.8771
Epoch 13/30
210/210 - 0s - loss: 0.3875 - accuracy: 0.8824
Epoch 14/30
210/210 - 0s - loss: 0.3704 - accuracy: 0.8938
Epoch 15/30
210/210 - 0s - loss: 0.3553 - accuracy: 0.9033
Epoch 16/30
210/210 - 0s - loss: 0.3422 - accuracy: 0.9052
Epoch 17/30
210/210 - 0s - loss: 0.3308 - accuracy: 0.9138
Epoch 

## Build a validation set using Keras

In [14]:
model.fit(x=scaled_train_samples,y=train_labels,validation_split=0.1,batch_size=10,epochs=30,shuffle=True,verbose=2)

Epoch 1/30
189/189 - 0s - loss: 0.2656 - accuracy: 0.9434 - val_loss: 0.2980 - val_accuracy: 0.9238
Epoch 2/30
189/189 - 0s - loss: 0.2641 - accuracy: 0.9376 - val_loss: 0.2968 - val_accuracy: 0.9238
Epoch 3/30
189/189 - 0s - loss: 0.2629 - accuracy: 0.9402 - val_loss: 0.2961 - val_accuracy: 0.9238
Epoch 4/30
189/189 - 0s - loss: 0.2618 - accuracy: 0.9381 - val_loss: 0.2951 - val_accuracy: 0.9333
Epoch 5/30
189/189 - 0s - loss: 0.2606 - accuracy: 0.9429 - val_loss: 0.2946 - val_accuracy: 0.9238
Epoch 6/30
189/189 - 0s - loss: 0.2597 - accuracy: 0.9407 - val_loss: 0.2937 - val_accuracy: 0.9333
Epoch 7/30
189/189 - 0s - loss: 0.2588 - accuracy: 0.9439 - val_loss: 0.2932 - val_accuracy: 0.9333
Epoch 8/30
189/189 - 0s - loss: 0.2578 - accuracy: 0.9418 - val_loss: 0.2927 - val_accuracy: 0.9333
Epoch 9/30
189/189 - 0s - loss: 0.2571 - accuracy: 0.9450 - val_loss: 0.2923 - val_accuracy: 0.9333
Epoch 10/30
189/189 - 0s - loss: 0.2564 - accuracy: 0.9429 - val_loss: 0.2918 - val_accuracy: 0.9333

## Predict data from a test set (Inference)
### Preprocess text data

In [15]:
test_labels = []
test_samples = []

In [16]:
for i in range(50):
    #5% of young people experienced side effects
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    #5% of older people did not experience side effects
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(1000):
    #95% of young people did not experience side effects
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    #95% of older people did experience side effects
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)

In [17]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)
test_labels, train_samples = shuffle(test_labels, test_samples)

scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

## Predict on test data

In [18]:
predictions = model.predict(x=scaled_test_samples,batch_size=10,verbose=0)

In [19]:
for i in predictions:
    print(i)

[0.9667568  0.03324322]
[0.09663813 0.90336186]
[0.9667437  0.03325628]
[0.04921981 0.95078015]
[0.95063245 0.04936752]
[0.02703721 0.9729628 ]
[0.52489847 0.47510153]
[0.01469741 0.98530257]
[0.95600945 0.04399051]
[0.07998642 0.92001355]
[0.9667175  0.03328244]
[0.04037359 0.95962644]
[0.87603533 0.12396464]
[0.01469741 0.98530257]
[0.96676195 0.03323809]
[0.07998642 0.92001355]
[0.96672744 0.03327263]
[0.05988338 0.94011664]
[0.958484   0.04151603]
[0.05988338 0.94011664]
[0.96676004 0.03323994]
[0.07268064 0.92731935]
[0.96230656 0.03769341]
[0.02990288 0.97009706]
[0.96674705 0.03325301]
[0.30402777 0.6959722 ]
[0.96082497 0.03917503]
[0.14728475 0.8527153 ]
[0.92241865 0.07758138]
[0.04458803 0.955412  ]
[0.9667372  0.03326282]
[0.07268064 0.92731935]
[0.9667372  0.03326282]
[0.02443923 0.9755608 ]
[0.89482325 0.10517678]
[0.23159312 0.76840687]
[0.9446363 0.0553637]
[0.05430544 0.94569457]
[0.96676195 0.03323809]
[0.01627708 0.983723  ]
[0.91087234 0.08912759]
[0.09663813 0.9033

[0.43254614 0.56745386]
[0.9667339  0.03326609]
[0.07268064 0.92731935]
[0.96672744 0.03327263]
[0.04458803 0.955412  ]
[0.96676195 0.03323809]
[0.02990288 0.97009706]
[0.96676195 0.03323809]
[0.02990288 0.97009706]
[0.958484   0.04151603]
[0.01627708 0.983723  ]
[0.9667339  0.03326609]
[0.02443923 0.9755608 ]
[0.92241865 0.07758138]
[0.12776229 0.8722377 ]
[0.96671426 0.0332857 ]
[0.20022142 0.7997786 ]
[0.96676195 0.03323809]
[0.01995332 0.98004675]
[0.9637095  0.03629058]
[0.04921981 0.95078015]
[0.96671104 0.03328897]
[0.05988338 0.94011664]
[0.9667175  0.03328244]
[0.01802341 0.9819766 ]
[0.9667175  0.03328244]
[0.26624385 0.7337562 ]
[0.8019759  0.19802408]
[0.38768733 0.6123127 ]
[0.95063245 0.04936752]
[0.34465525 0.6553447 ]
[0.92241865 0.07758138]
[0.34465525 0.6553447 ]
[0.9667437  0.03325628]
[0.10607659 0.89392346]
[0.87603533 0.12396464]
[0.10607659 0.89392346]
[0.96674705 0.03325301]
[0.06599434 0.9340056 ]
[0.85443735 0.14556262]
[0.01469741 0.98530257]
[0.82980746 0.17

[0.96230656 0.03769341]
[0.00975627 0.99024373]
[0.96676195 0.03323809]
[0.07268064 0.92731935]
[0.91087234 0.08912759]
[0.11631816 0.88368183]
[0.9667339  0.03326609]
[0.14728475 0.8527153 ]
[0.8019759  0.19802408]
[0.43254614 0.56745386]
[0.96676195 0.03323809]
[0.05430544 0.94569457]
[0.9446363 0.0553637]
[0.05988338 0.94011664]
[0.96676195 0.03323809]
[0.02443923 0.9755608 ]
[0.96549046 0.03450957]
[0.08795683 0.91204315]
[0.95063245 0.04936752]
[0.07268064 0.92731935]
[0.9667535  0.03324648]
[0.11631816 0.88368183]
[0.96627533 0.03372466]
[0.01326899 0.98673105]
[0.9446363 0.0553637]
[0.07998642 0.92001355]
[0.7364394  0.26356062]
[0.01802341 0.9819766 ]
[0.9667437  0.03325628]
[0.01326899 0.98673105]
[0.52489847 0.47510153]
[0.05988338 0.94011664]
[0.958484   0.04151603]
[0.00975627 0.99024373]
[0.96676195 0.03323809]
[0.03306201 0.966938  ]
[0.96676195 0.03323809]
[0.01995332 0.98004675]
[0.958484   0.04151604]
[0.02208523 0.9779148 ]
[0.941387   0.05861306]
[0.34465525 0.655344

In [20]:
rounded_predictions = np.argmax(predictions,axis=-1)

In [21]:
for i in rounded_predictions:
    print(i)

0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1


## Confusion Matrix

In [22]:
%matplotlib inline
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [23]:
cm = confusion_matrix(y_true=test_labels,y_pred=rounded_predictions)

In [25]:

def plot_confusion_matrix(cm,classes,normalize=False,title='Confusion Matrix',cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix
    """
    plt.imshow(cm,interpolation='nearest',cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks,classes,rotation=45)
    plt.yticks(tick_marks,classes)
    
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:,np.newaxis]
        print("Normalized Confusion Matrix")
    else:
        print("Confusion Matrix, without normalization")
        
    print(cm)
    
    thresh = cm.max()/2
    #for i,j in itertools.product(range(cm.shape[0],range))
    
    
    

## Save and Load Keras model

In [27]:
import os.path
if os.path.isfile('models/medical_trial_model.h5') is False:
    model.save('models/medical_trial_model.h5')

In [28]:
from tensorflow.keras.models import load_model
new_model = load_model('models/medical_trial_model.h5')

In [30]:
new_model.get_weights()

[array([[-0.21143883, -0.2927317 , -0.56783354, -0.55617064, -0.19531235,
         -0.29099292, -0.31019613, -0.10082301,  0.5158068 ,  0.37176523,
         -0.146889  , -0.26365733,  0.34914833,  0.5122294 , -0.07253504,
          0.67959446]], dtype=float32),
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , -0.14649543, -0.14727807,
         0.        ,  0.        , -0.02178843, -0.15876938,  0.        ,
        -0.16745403], dtype=float32),
 array([[ 0.1778886 , -0.05422884, -0.10747303,  0.10976827, -0.2026037 ,
          0.26679966,  0.2250844 ,  0.31058756, -0.03775144,  0.1791071 ,
         -0.15496056,  0.30526063,  0.0405553 , -0.08219376, -0.28686443,
          0.2525663 ,  0.01550457, -0.043127  ,  0.13663182, -0.32679063,
          0.21991912,  0.07359245, -0.27733755, -0.04310349,  0.32144943,
         -0.17000563, -0.08848369,  0.06356815,  0.2637652 ,  0.2896264 ,
         -0.02518249, -0.02012479],
 

In [31]:
new_model.optimizer